# Generated by Django 5.2.3 on 2025-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                    ("waiter", "Waiter"),
                    ("customer", "Customer"),
                    ("chef", "Chef"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
