# Generated by Django 5.2.6 on 2025-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasehistory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchasehistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
