# Generated by Django 5.2.3 on 2025-07-13 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0003_alter_menuitem_options_menuitem_discount_end_and_more"),
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("restaurant and cafe", "Restaurant and cafe"),
                            ("service", "Service"),
                            ("staff", "Staff"),
                            ("environment", "Environment"),
                        ],
                        default="restaurant and cafe",
                        max_length=20,
                    ),
                ),
                (
                    "food_rating",
                    models.CharField(
                        choices=[
                            ("1", "1 - Terrible"),
                            ("2", "2 - Very Bad"),
                            ("3", "3 - Bad"),
                            ("4", "4 - Not Good"),
                            ("5", "5 - Average"),
                            ("6", "6 - Okay"),
                            ("7", "7 - Good"),
                            ("8", "8 - Very Good"),
                            ("9", "9 - Excellent"),
                            ("10", "10 - Perfect"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "service_satisfaction",
                    models.CharField(
                        choices=[("1", "Yes"), ("2", "Somewhat"), ("3", "No")],
                        max_length=2,
                    ),
                ),
                (
                    "staff_behavior",
                    models.CharField(
                        choices=[("1", "Yes"), ("2", "Somewhat"), ("3", "No")],
                        max_length=2,
                    ),
                ),
                (
                    "cleanliness",
                    models.CharField(
                        choices=[("1", "Yes"), ("2", "Somewhat"), ("3", "No")],
                        max_length=2,
                    ),
                ),
                (
                    "preparation_time",
                    models.CharField(
                        choices=[("1", "Yes"), ("2", "Somewhat"), ("3", "No")],
                        max_length=2,
                    ),
                ),
                (
                    "revisit_intent",
                    models.CharField(
                        choices=[("1", "Yes"), ("2", "Somewhat"), ("3", "No")],
                        max_length=2,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("admin_response", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("reviewed", "Reviewed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
                "unique_together": {("user", "order", "item")},
            },
        ),
    ]
