# Generated by Django 5.2.3 on 2025-07-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together=set(),
        ),
    ]
