# Generated by Django 5.2.3 on 2025-07-15 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedback_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
