# Generated by Django 5.2.6 on 2025-10-29 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient_requests", "0002_ingredientitem_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ingredientitem",
            index=models.Index(
                fields=["request"], name="ingredient__request_9bd55a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredientitem",
            index=models.Index(fields=["name"], name="ingredient__name_8aa3e4_idx"),
        ),
        migrations.AddIndex(
            model_name="ingredientitem",
            index=models.Index(
                fields=["request", "name"], name="ingredient__request_2cae9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredientrequest",
            index=models.Index(fields=["chef"], name="ingredient__chef_id_e90ed6_idx"),
        ),
        migrations.AddIndex(
            model_name="ingredientrequest",
            index=models.Index(
                fields=["is_reviewed", "created_at"],
                name="ingredient__is_revi_80a6be_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientitem",
            constraint=models.UniqueConstraint(
                fields=("request", "name"), name="unique_item_per_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_approved", True), ("is_rejected", True), _negated=True
                ),
                name="approved_not_rejected",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientrequest",
            constraint=models.UniqueConstraint(
                fields=("chef", "note"), name="unique_request_per_chef"
            ),
        ),
    ]
