# Generated by Django 5.2.3 on 2025-07-15 09:10

import info.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_workinghours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="phone_number",
            field=models.CharField(
                max_length=8,
                validators=[info.validators.validate_company_phone_number],
                verbose_name="Contact number",
            ),
        ),
    ]
