# Generated by Django 5.2.6 on 2025-10-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_aboutus_deleted_at_contactus_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "About Us",
                "verbose_name_plural": "About Us Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Us",
                "verbose_name_plural": "Contact Information",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalaboutus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical About Us",
                "verbose_name_plural": "historical About Us Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontactus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Contact Us",
                "verbose_name_plural": "historical Contact Information",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalworkinghours",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Working Hour",
                "verbose_name_plural": "historical Working Hours",
            },
        ),
        migrations.AlterModelOptions(
            name="workinghours",
            options={
                "ordering": ["day"],
                "verbose_name": "Working Hour",
                "verbose_name_plural": "Working Hours",
            },
        ),
        migrations.AddField(
            model_name="aboutus",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="contactus",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="contactus",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="contactus",
            name="social_links",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Social Links"
            ),
        ),
        migrations.AddField(
            model_name="historicalaboutus",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactus",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="historicalcontactus",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactus",
            name="social_links",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Social Links"
            ),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="historicalaboutus",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="historicalaboutus",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="historicalworkinghours",
            name="close_time",
            field=models.TimeField(verbose_name="Closing Time"),
        ),
        migrations.AlterField(
            model_name="historicalworkinghours",
            name="day",
            field=models.CharField(
                choices=[
                    ("sat", "Saturday"),
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                ],
                help_text="Select the weekday this schedule applies to.",
                max_length=3,
                verbose_name="Day",
            ),
        ),
        migrations.AlterField(
            model_name="historicalworkinghours",
            name="open_time",
            field=models.TimeField(verbose_name="Opening Time"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="close_time",
            field=models.TimeField(verbose_name="Closing Time"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="day",
            field=models.CharField(
                choices=[
                    ("sat", "Saturday"),
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                ],
                help_text="Select the weekday this schedule applies to.",
                max_length=3,
                verbose_name="Day",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="open_time",
            field=models.TimeField(verbose_name="Opening Time"),
        ),
        migrations.AddIndex(
            model_name="aboutus",
            index=models.Index(fields=["title"], name="info_aboutu_title_2bdcca_idx"),
        ),
        migrations.AddIndex(
            model_name="contactus",
            index=models.Index(
                fields=["phone_number"], name="info_contac_phone_n_ccab62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workinghours",
            index=models.Index(fields=["day"], name="info_workin_day_79c92c_idx"),
        ),
        migrations.AddIndex(
            model_name="workinghours",
            index=models.Index(
                fields=["day", "open_time"], name="info_workin_day_43e3c2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workinghours",
            constraint=models.CheckConstraint(
                condition=models.Q(("close_time__gt", models.F("open_time"))),
                name="valid_working_hours",
            ),
        ),
        migrations.AddConstraint(
            model_name="workinghours",
            constraint=models.UniqueConstraint(
                fields=("day",), name="unique_working_day"
            ),
        ),
    ]
