# Generated by Django 5.2.3 on 2025-07-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_menuitem_discount_percent_menuitem_is_special_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Menu item",
                "verbose_name_plural": "Menu items",
            },
        ),
        migrations.AddField(
            model_name="menuitem",
            name="discount_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="discount_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
