# Generated by Django 5.2.6 on 2025-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_category_deleted_at_menuitem_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="sold_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
