# Generated by Django 5.2.6 on 2025-10-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_menuitem_sold_count"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["name"], name="menu_menuit_name_138666_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category", "status"], name="menu_menuit_categor_fa258f_idx"
            ),
        ),
    ]
