# Generated by Django 5.2.3 on 2025-07-01 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Table Number"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        choices=[
                            ("2", "2 solo"),
                            ("4", "4 solo"),
                            ("8", "8 solo"),
                            ("10", "10 solo"),
                        ],
                        verbose_name="Capacity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full Name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                ("date", models.DateField(verbose_name="Day")),
                ("time", models.TimeField(verbose_name="Time")),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(verbose_name="Number of Guests"),
                ),
                (
                    "table_type",
                    models.CharField(
                        choices=[
                            ("2", "2 solo"),
                            ("4", "4 solo"),
                            ("8", "8 solo"),
                            ("10", "10 solo"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "extra_notes",
                    models.TextField(blank=True, null=True, verbose_name="Extra Notes"),
                ),
                (
                    "reservation_type",
                    models.CharField(
                        choices=[("normal", "Normal"), ("birthday", "Birthday")],
                        default="normal",
                        max_length=20,
                        verbose_name="Reservation Type",
                    ),
                ),
                (
                    "birthday_design",
                    models.BooleanField(
                        default=False, verbose_name="Birthday Decoration"
                    ),
                ),
                (
                    "birthday_cake",
                    models.BooleanField(default=False, verbose_name="Birthday Cake"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        choices=[
                            (60, "60 Minutes"),
                            (90, "90 Minutes"),
                            (120, "120 Minutes"),
                            (150, "150 Minutes"),
                        ],
                        default=60,
                        verbose_name="Duration (minutes)",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Approved by Admin"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.table",
                        verbose_name="Selected Table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
                "ordering": ["-created_date"],
            },
        ),
    ]
