# Generated by Django 5.2.3 on 2025-07-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="created_date",
        ),
    ]
