# Generated by Django 5.2.3 on 2025-07-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="capacity",
            field=models.CharField(
                choices=[
                    ("2", "2 solo"),
                    ("4", "4 solo"),
                    ("8", "8 solo"),
                    ("10", "10 solo"),
                ],
                max_length=2,
                verbose_name="Capacity",
            ),
        ),
    ]
