# Generated by Django 5.2.3 on 2025-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_alter_table_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="table_type",
            field=models.CharField(
                choices=[
                    ("2", "2 solo"),
                    ("4", "4 solo"),
                    ("8", "8 solo"),
                    ("10", "10 solo"),
                ],
                max_length=2,
                verbose_name="Table Type",
            ),
        ),
    ]
