# Generated by Django 5.2.6 on 2025-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_alter_reservation_table_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
