# Generated by Django 5.2.6 on 2025-10-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_reservation_deleted_at_alter_reservation_created_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["date", "time"], name="reservation_date_69bfbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["table", "date", "time"], name="reservation_table_i_6731a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["is_approved"], name="reservation_is_appr_253242_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(fields=["number"], name="reservation_number_319f48_idx"),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("number_of_guests__gt", 0)),
                name="positive_number_of_guests",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration__in", [60, 90, 120, 150])),
                name="valid_reservation_duration",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("table_type__in", ["2", "4", "8", "10"])),
                name="valid_table_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("reservation_type__in", ["normal", "birthday"])),
                name="valid_reservation_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__in", ["2", "4", "8", "10"])),
                name="valid_table_capacity",
            ),
        ),
    ]
