# Generated by Django 5.2.6 on 2025-10-29 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_menuitem_menu_menuit_name_138666_idx_and_more"),
        ("orders", "0004_order_deleted_at_order_payment_status_and_more"),
        ("reservation", "0005_reservation_deleted_at_alter_reservation_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["is_paid"], name="orders_invo_is_paid_816fea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "menu_item"], name="orders_orde_order_i_5d7cf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="orders_paym_status_83f434_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "status"], name="orders_paym_order_i_e3de73_idx"
            ),
        ),
    ]
